on:
  push:
    branches:
      - master

jobs:
  test:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/cache@v1
      with:
        path: node_modules
        id: cache
        key: node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-
    - name: Install Packages
      run: npm install
    - name: Test
      run: npm run test
